# Generated by Django 2.0.3 on 2018-03-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_descriptor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Работник кафедры', 'verbose_name_plural': 'Работники кафедры'},
        ),
        migrations.AlterField(
            model_name='person',
            name='descriptor',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Дескриптор'),
        ),
    ]
